In [1]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv("iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
#get the shape of the dataset
data.shape

(150, 6)

In [7]:
#get the value count of the Species column in the dataset
data['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [9]:
#can use this method to get an idea about the data set
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [11]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
#seperate the data sets to x, y
x = data.iloc[:,1:5]
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [14]:
y = data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [17]:
#use the feature scaling the X values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)
x[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [19]:
x_train.shape
#(number of data for x_train, number of columns)

(120, 4)

In [20]:
x_test.shape

(30, 4)

In [21]:
#train using KNN algorithm
from sklearn.neighbors import KNeighborsClassifier
#creating an object for the model
model = KNeighborsClassifier(n_neighbors=1)
#train using training datasets x,y
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [22]:
#predict the values
pred = model.predict(x_test)
pred[0:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [23]:
y_test[0:5]

10    Iris-setosa
15    Iris-setosa
0     Iris-setosa
47    Iris-setosa
45    Iris-setosa
Name: Species, dtype: object

In [25]:
#finding the accuracy of the model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, pred)
accuracy

0.9333333333333333

In [26]:
#another way to get the accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
cm

array([[15,  0,  0],
       [ 0,  8,  2],
       [ 0,  0,  5]], dtype=int64)

In [30]:
#getting more description about the trained data model
result = pd.DataFrame(data=[y_test.values, pred], index =['y_test','predicated'])
result.transpose()

y_test       predicated
0       Iris-setosa      Iris-setosa
1       Iris-setosa      Iris-setosa
2       Iris-setosa      Iris-setosa
3       Iris-setosa      Iris-setosa
4       Iris-setosa      Iris-setosa
5       Iris-setosa      Iris-setosa
6   Iris-versicolor   Iris-virginica
7   Iris-versicolor  Iris-versicolor
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15   Iris-virginica   Iris-virginica
16  Iris-versicolor  Iris-versicolor
17   Iris-virginica   Iris-virginica
18   Iris-virginica   Iris-virginica
19  Iris-versicolor   Iris-virginica
20      Iris-setosa      Iris-setosa
21  Iris-versicolor  Iris-versicolor
22   Iris-virginica   Iris-virginica
23      Iris-setosa      Iris-setosa
24      Iris-setosa      Iris-setosa
25  Iris-versicolor  Iris-versicolor
26  Iris-versicolor  Iris-versicolor
27      Iris-setosa      Iris-setosa
28  Iris-versicolor  Iris-versicolor
29   Iris-virginica   Iris-virginica

In [31]:
#finding the most appropriate K values
correct_sum = []
for i  in range(1,20):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    pred = model.predict(x_test)
    correct = np.sum(pred == y_test)
    correct_sum.append(correct)

In [32]:
correct_sum

[28, 28, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28]

In [35]:
#show this as a dataframe
result = pd.DataFrame(data=correct_sum)
result.index = result.index+1
result.T

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19
0  28  28  27  28  28  28  28  28  28  28  28  28  28  28  28  28  28  28  28

In [37]:
#now we are going to train and predict using a selected K value = 8
model = KNeighborsClassifier(n_neighbors=8)
model.fit(x_train, y_train)
pred = model.predict(x_test)

In [38]:
#getting the accuracy
accuracy_score(y_test, pred)

0.9333333333333333

In [39]:
#show using confusion matrix
confusion_matrix(y_test, pred)

array([[15,  0,  0],
       [ 0,  8,  2],
       [ 0,  0,  5]], dtype=int64)